// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package msg

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Data struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Date                 string   `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Author               string   `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	Id                   int32    `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Data) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Data) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Data) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Data) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Data) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RequestId struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestId) Reset()         { *m = RequestId{} }
func (m *RequestId) String() string { return proto.CompactTextString(m) }
func (*RequestId) ProtoMessage()    {}
func (*RequestId) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *RequestId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestId.Unmarshal(m, b)
}
func (m *RequestId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestId.Marshal(b, m, deterministic)
}
func (m *RequestId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestId.Merge(m, src)
}
func (m *RequestId) XXX_Size() int {
	return xxx_messageInfo_RequestId.Size(m)
}
func (m *RequestId) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestId.DiscardUnknown(m)
}

var xxx_messageInfo_RequestId proto.InternalMessageInfo

func (m *RequestId) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Data)(nil), "Data")
	proto.RegisterType((*RequestId)(nil), "RequestId")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xb1, 0xca, 0xc2, 0x30,
	0x14, 0x85, 0xff, 0xf4, 0x6f, 0x2a, 0xbd, 0x05, 0x87, 0x8b, 0x48, 0xd0, 0xa5, 0x64, 0xea, 0x62,
	0x07, 0x7d, 0x03, 0x71, 0xe9, 0xda, 0x37, 0x88, 0x26, 0xd4, 0x80, 0x9a, 0xda, 0xdc, 0x0e, 0xbe,
	0x84, 0xcf, 0x2c, 0xc6, 0x58, 0xdc, 0xce, 0xf9, 0x3e, 0x2e, 0xdc, 0x03, 0xf9, 0xd5, 0x77, 0x75,
	0x3f, 0x38, 0x72, 0xf2, 0xc9, 0x20, 0x3d, 0x28, 0x52, 0xb8, 0x00, 0x4e, 0x96, 0x2e, 0x46, 0xb0,
	0x92, 0x55, 0x79, 0xfb, 0x29, 0x88, 0x90, 0x6a, 0x45, 0x46, 0x24, 0x01, 0x86, 0x1c, 0x99, 0x12,
	0xff, 0x13, 0x53, 0x58, 0x42, 0xa1, 0x8d, 0x3f, 0x0d, 0xb6, 0x27, 0xeb, 0x6e, 0x22, 0x0d, 0xea,
	0x17, 0xe1, 0x12, 0x32, 0x35, 0xd2, 0xd9, 0x0d, 0x82, 0x07, 0x19, 0x1b, 0xce, 0x21, 0xb1, 0x5a,
	0x64, 0x25, 0xab, 0x78, 0x9b, 0x58, 0x2d, 0xd7, 0x90, 0xb7, 0xe6, 0x3e, 0x1a, 0x4f, 0x8d, 0x8e,
	0x92, 0x7d, 0xe5, 0x76, 0x03, 0xb3, 0xce, 0x50, 0xf8, 0x57, 0x42, 0x11, 0xe3, 0xfe, 0xd1, 0x68,
	0x84, 0x7a, 0xba, 0x5a, 0xf1, 0xfa, 0x8d, 0xe5, 0xdf, 0x31, 0x0b, 0x1b, 0x77, 0xaf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xc3, 0xe6, 0x4f, 0x63, 0xf0, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GetDataClient is the client API for GetData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GetDataClient interface {
	GetDataById(ctx context.Context, in *RequestId, opts ...grpc.CallOption) (*Data, error)
}

type getDataClient struct {
	cc *grpc.ClientConn
}

func NewGetDataClient(cc *grpc.ClientConn) GetDataClient {
	return &getDataClient{cc}
}

func (c *getDataClient) GetDataById(ctx context.Context, in *RequestId, opts ...grpc.CallOption) (*Data, error) {
	out := new(Data)
	err := c.cc.Invoke(ctx, "/getData/getDataById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetDataServer is the server API for GetData service.
type GetDataServer interface {
	GetDataById(context.Context, *RequestId) (*Data, error)
}

// UnimplementedGetDataServer can be embedded to have forward compatible implementations.
type UnimplementedGetDataServer struct {
}

func (*UnimplementedGetDataServer) GetDataById(ctx context.Context, req *RequestId) (*Data, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDataById not implemented")
}

func RegisterGetDataServer(s *grpc.Server, srv GetDataServer) {
	s.RegisterService(&_GetData_serviceDesc, srv)
}

func _GetData_GetDataById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetDataServer).GetDataById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/getData/GetDataById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetDataServer).GetDataById(ctx, req.(*RequestId))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetData_serviceDesc = grpc.ServiceDesc{
	ServiceName: "getData",
	HandlerType: (*GetDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getDataById",
			Handler:    _GetData_GetDataById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "msg.proto",
}
